# Configuration for 8B Mixture-of-Transformers with 2 modalities (text + image)
# Similar to Chameleon setting

[job]
dump_folder = "./outputs"
description = "MoT 8B 2-modality training (text + image)"
print_config = false

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 10
disable_color_printing = false
enable_tensorboard = true
save_tb_folder = "tb"
enable_wandb = false

[model]
name = "mot"
flavor = "8B_2modality"
# Path to tokenizer assets
hf_assets_path = "./assets/tokenizer"

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8
weight_decay = 0.1
betas = [0.9, 0.95]

[lr_scheduler]
warmup_steps = 2000  # lr scheduler warm up, normally 20% of the train steps
decay_ratio = 0.8  # lr scheduler decay ratio, 80% of the train steps
decay_type = "cosine"
min_lr_factor = 0.1

[training]
local_batch_size = 2
seq_len = 8192
max_norm = 1.0  # grad norm clipping
steps = 100000
dataset = "c4"  # supported datasets: c4_test (2K), c4 (177M)
mixed_precision_param = "bfloat16"
mixed_precision_reduce = "float32"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 4
enable_async_tensor_parallel = false

[checkpoint]
enable = true
folder = "checkpoint"
interval = 1000
last_save_model_only = false
export_dtype = "bfloat16"
async_mode = "async_with_pinned_mem"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "selective"  # ["none", "selective", "full"]
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[compile]
enable = true
components = ["model"]

[validation]
enable = true
dataset = "c4_validation"
freq = 500
steps = 100
